#! /bin/sh
""":"
exec python $0 ${1+"$@"}
"""


def main():
    print("""
[
    {
        "name": "com.ubuntu.developer.testclick",
        "architecture": "all",
        "framework": "ubuntu-sdk-14.10",
        "installed-size": "709",
        "version": "0.1"
    }
]
    """)

if __name__ == "__main__":
    # execute only if run as a script
    main()
