/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp agent.xml -a agentadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "agentadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Agent1Adaptor
 */

Agent1Adaptor::Agent1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Agent1Adaptor::~Agent1Adaptor()
{
    // destructor
}

void Agent1Adaptor::AuthorizeService(const QDBusObjectPath &device, const QString &uuid)
{
    // handle method call org.bluez.Agent1.AuthorizeService
    QMetaObject::invokeMethod(parent(), "AuthorizeService", Q_ARG(QDBusObjectPath, device), Q_ARG(QString, uuid));
}

void Agent1Adaptor::Cancel()
{
    // handle method call org.bluez.Agent1.Cancel
    QMetaObject::invokeMethod(parent(), "Cancel");
}

void Agent1Adaptor::DisplayPasskey(const QDBusObjectPath &device, uint passkey, ushort entered)
{
    // handle method call org.bluez.Agent1.DisplayPasskey
    QMetaObject::invokeMethod(parent(), "DisplayPasskey", Q_ARG(QDBusObjectPath, device), Q_ARG(uint, passkey), Q_ARG(ushort, entered));
}

void Agent1Adaptor::DisplayPinCode(const QDBusObjectPath &device, const QString &pincode)
{
    // handle method call org.bluez.Agent1.DisplayPinCode
    QMetaObject::invokeMethod(parent(), "DisplayPinCode", Q_ARG(QDBusObjectPath, device), Q_ARG(QString, pincode));
}

void Agent1Adaptor::Release()
{
    // handle method call org.bluez.Agent1.Release
    QMetaObject::invokeMethod(parent(), "Release");
}

void Agent1Adaptor::RequestAuthorization(const QDBusObjectPath &device)
{
    // handle method call org.bluez.Agent1.RequestAuthorization
    QMetaObject::invokeMethod(parent(), "RequestAuthorization", Q_ARG(QDBusObjectPath, device));
}

void Agent1Adaptor::RequestConfirmation(const QDBusObjectPath &device, uint passkey)
{
    // handle method call org.bluez.Agent1.RequestConfirmation
    QMetaObject::invokeMethod(parent(), "RequestConfirmation", Q_ARG(QDBusObjectPath, device), Q_ARG(uint, passkey));
}

uint Agent1Adaptor::RequestPasskey(const QDBusObjectPath &device)
{
    // handle method call org.bluez.Agent1.RequestPasskey
    uint passkey;
    QMetaObject::invokeMethod(parent(), "RequestPasskey", Q_RETURN_ARG(uint, passkey), Q_ARG(QDBusObjectPath, device));
    return passkey;
}

QString Agent1Adaptor::RequestPinCode(const QDBusObjectPath &device)
{
    // handle method call org.bluez.Agent1.RequestPinCode
    QString pincode;
    QMetaObject::invokeMethod(parent(), "RequestPinCode", Q_RETURN_ARG(QString, pincode), Q_ARG(QDBusObjectPath, device));
    return pincode;
}

